name: dosbox-x
adopt-info: dosbox-x
base: core22

architectures:
  - build-on: i386
  - build-on: amd64

confinement: strict
grade: stable

assumes:
  - snapd2.36 # layouts

layout:
  /usr/share/dosbox-x:
    bind: $SNAP/usr/share/dosbox-x
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds

apps:
  dosbox-x:
    command: bin/desktop-launch $SNAP/usr/bin/dosbox-x
    desktop: usr/share/applications/com.dosbox_x.DOSBox-X.desktop
    common-id: com.dosbox_x.DOSBox-X
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs: 
    - audio-playback
    - desktop
    - desktop-legacy
    - home
    - network
    - network-bind
    - opengl
    - raw-usb
    - removable-media
    - serial-port
    - unity7
    - wayland
    - x11

parts:
  dosbox-x:
    plugin: autotools
    after: [desktop-glib-only,ffmpeg]
    parse-info: [usr/share/metainfo/com.dosbox_x.DOSBox-X.metainfo.xml]
    source-type: git
    source: https://github.com/joncampbell123/dosbox-x.git
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-debug=heavy
      - --enable-sdl2
    build-environment:
      - LD_LIBRARY_PATH: ${CRAFT_STAGE}/usr/lib
    override-build: |
        # There is no pattern in the release tags for DosBox-X
        # This should resolve to a version or datestamp or both.
        last_committed_tag="$(git describe --tags --abbrev=0)"
        last_committed_tag_ver="$(echo ${last_committed_tag} | sed -e 's/dosbox-x-//' -e 's/wip-//' -e 's/windows-//' -e 's/v//')"
        last_released_tag="$(snap info dosbox-x | awk '$1 == "latest/beta:" { print $2 }')"
        # If the latest tag from the upstream project has not been released to
        # beta, build that tag instead of master.
        if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
          git fetch
          git checkout "${last_committed_tag}"
        fi

        snapcraftctl build

        # never fail on the next line (use `|| true` to ignore errors)
        desktop-file-edit --set-key=Icon --set-value='${SNAP}/usr/share/icons/hicolor/scalable/apps/dosbox-x.svg' $SNAPCRAFT_PART_INSTALL/usr/share/applications/com.dosbox_x.DOSBox-X.desktop || true
    build-packages:
      - desktop-file-utils
      - g++
      - libasound2-dev
      - libncurses5-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-net-dev
      - libfluidsynth-dev
      - libxkbfile-dev
      - make
      - nasm
    stage-packages:
      - fluid-soundfont-gm
      - libasound2
      - libbluray2
      - libfluidsynth3
      - libfontconfig1
      - libglu1-mesa
      - libgme0
      - libgsm1
      - libjpeg62
      - libmodplug1
      - libmp3lame0
      - libnuma1
      - libogg0
      - libopus0
      - liborc-0.4-0
      - libpng16-16
      - libpulse0
      - librtmp1
      - libsdl2-2.0-0
      - libsdl2-net-2.0-0
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libtheora0
      - libtwolame0
      - libva2
      - libvorbis0a
      - libvorbisenc2
      - libvpx7
      - libwavpack1
      - libwebp7
      - libx264-163
      - libx265-199
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxkbfile1
      - libxml2
      - libxvidcore4
      - libzvbi0
      - yad # for dosbox to open dialogs

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  nv-codec-headers:
    plugin: make
    source: https://github.com/FFmpeg/nv-codec-headers.git
    source-branch: 'old/sdk/10.0'
    override-build: |
      make install PREFIX=/usr
    build-packages:
      - pkg-config

  fdk-aac:
    plugin: autotools
    source: https://github.com/mstorsjo/fdk-aac/archive/v2.0.2.tar.gz
    build-packages:
      - g++
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-static
    prime:
      - usr/lib
      - usr/lib/pkgconfig
      - usr/include

  ffmpeg:
    plugin: autotools
    source: https://github.com/FFmpeg/FFmpeg.git
    source-branch: release/4.4
    after:
      - nv-codec-headers
      - fdk-aac
    build-packages:
      - libass-dev
      - libbz2-dev
      - libdrm-dev
      - libgnutls28-dev
      - liblzma-dev
      - libmp3lame-dev
      - libomxil-bellagio-dev
      - libopenal-dev
      - libopencore-amrnb-dev
      - libopencore-amrwb-dev
      - libopus-dev
      - libpulse-dev
      - libsctp-dev
      - libsdl2-dev
      - libspeex-dev
      - libtheora-dev
      - libtwolame-dev
      - libv4l-dev
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libvpx-dev
      - libx264-dev
      - libx265-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxv-dev
      - libxvidcore-dev
      - ocl-icd-opencl-dev
      - opencl-headers
      - pkg-config
      - yasm
    stage-packages:
      - libass9
      - libdrm2
      - libgnutls30
      - libmp3lame0
      - libopenal1
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopus0
      - libpulse0
      - libsdl2-2.0-0
      - libspeex1
      - libtheora0
      - libtwolame0
      - libv4l-0
      - libv4l2rds0
      - libva-drm2
      - libva-glx2
      - libva-wayland2
      - libvdpau-va-gl1
      - libvorbis0a
      - libvorbisenc2
      - libvpx7
      - libx11-6
      - libx264-163
      - libx265-199
      - libxau6
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxv1
      - libxvidcore4
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - ocl-icd-libopencl1
      - on amd64:
        - i965-va-driver
      - on i386:
        - i965-va-driver
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-cuda
      - --enable-cuvid
      - --enable-libdrm
      - --enable-ffplay
      - --enable-gnutls
      - --enable-gpl
      - --enable-libass
      - --enable-libfdk-aac
      - --enable-libfontconfig
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libopencore_amrnb
      - --enable-libopencore_amrwb
      - --enable-libopus
      - --enable-libpulse
      - --enable-sdl2
      - --enable-libspeex
      - --enable-libtheora
      - --enable-libtwolame
      - --enable-libv4l2
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libx264
      - --enable-libx265
      - --enable-libxcb
      - --enable-libxvid
      - --enable-nonfree
      - --enable-nvenc
      - --enable-omx
      - --enable-openal
      - --enable-opencl
      - --enable-runtime-cpudetect
      - --enable-shared
      - --enable-vaapi
      - --enable-vdpau
      - --enable-version3
      - --enable-xlib
    prime:
      - usr/bin
      - usr/lib
      - usr/lib/pkgconfig
      - usr/include
      - -usr/share/doc
      - -usr/share/man
